### ISSUE TITLE
Report / Add scope (to support local/regional/... level report) and date

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/daobs#106]
Currently report generated only contains territory (ie. MS eg. FR) in the INSPIRE format.

Add more details about the context of the report:
* the date and time of creation of the report: if not provided, will be current date time but can be overridden using creationDate parameter. With #105, it will allows to follow trends with custom temporal steps.
* the filter which is applied in order to know on which subset a report is created on (ie. Solr query).
* the scope identifier which could be used to identify the report (eg. could override country code by a custom identifier eg. FR-Ifremer). Add the parameter scopeId=FR-Ifremer to the URL to override the value. The scope id will then be used as a key when submitting the report.

![image](https://cloud.githubusercontent.com/assets/1701393/14377850/4913b834-fd72-11e5-9512-6b30e5849179.png)

Should report in the output:

* in the dashboard XML format:
```
<reporting xmlns="http://daobs.org" 
  computationTime="549" 
  dateTime="2016-04-08T10:11:17.109+02:00" 
  scope="+territory:GEOPLATEFORME17 +Org:"Cdc Vals de Saintonge"" 
  scopeId="FR-Ifremer"
  id="inspire">
  <identification
```

* in INSPIRE reporting (eg. http://localhost:8983/daobs/reporting/custom/inspire/BDT32?fq=%20%2Bterritory%3ABDT32&organizationName=&email=&language=&creationDate=2012-02-06T12:02:02Z&scopeId=FR-Ifremer)

```
<ns2:Monitoring xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://inspire.jrc.ec.europa.eu/monitoringreporting/monitoring" xsi:schemaLocation="http://inspire.jrc.ec.europa.eu/monitoringreporting/monitoring http://dd.eionet.europa.eu/schemas/inspire-monitoring/monitoring.xsd">
<documentYear>
  <day>06</day>
  <month>02</month>
  <year>2012</year>
</documentYear>
<!--  Filter query:  +territory:BDT32 -->
<memberState>FR-Ifremer</memberState>
<MonitoringMD>...
```

Work supported by BRGM.

**Comment by phasenohr** [comment]
Wouldn't it be suitable to change the memberState name by default as soon as a filter is applied in order to avoid confusion when one reads INSPIRE monitoring files (otherwise no certainty that the content of the file is indeed related to the whole MS)?
