### ISSUE TITLE
Kibana config for IE

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/daobs#152]
In order to make it work under internet explorer, you should run this after the system is up:

```

curl -k --user $KIBANA_RW_USERNAME:$KIBANA_RW_PASSWORD -X POST -H "Content-Type: application/json" -H "kbn-xsrf: true" -d '{"value":true}' https://localhost:5601/api/kibana/settings/state:storeInSessionStorage

```

For avoiding annoying map warnings:

```

curl -k --user $KIBANA_RW_USERNAME:$KIBANA_RW_PASSWORD -X POST -H "Content-Type: application/json" -H "kbn-xsrf: true" -d '{"value":false}' https://localhost:5601/api/kibana/settings/visualization:regionmap:showWarnings

```

The catch is that you need to wait for the system to be up and running

Format numeric :  numeric layout set to: 0.[000]

Then dump with elasticdump to properly restore the config.

**Comment by michimau** [comment]
pls, set: state:storeInSessionStorage true

this will avoid problems with internet explorer
