### ISSUE TITLE
status of this platform

### ISSUE THREAD

**Issue by Seandebasti** [INSPIRE-MIF/daobs#177]
Via the INSPIRE country fiche I found this Kibana tool with 9+3 dashboards. It is really niche method to visualize the content of the monitoring.
Is this an active or passive platform https://inspire-dashboard.eea.europa.eu/#/

Is there an more recent version of the monitoring?
Thanks

**Comment by fxprunayre** [comment]
https://inspire-dashboard.eea.europa.eu/ is only used for browsing historical archive 2014-2019 and it is not updated anymore. The INSPIRE geoportal will provide more recent monitoring.

**Comment by Seandebasti** [comment]
thanks François, do you know which method will be used in the new monitoring? I was wondering if the [monitoring-bulk-validation-tool](https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool) is the base for this or not,
