### ISSUE TITLE
etf validation checker

### ISSUE THREAD

**Issue by Seandebasti** [INSPIRE-MIF/daobs#178]
Is there an working example of to show results with the dashboard "Service validation report (ETF)" ?
Thanks

**Comment by fxprunayre** [comment]
https://inspire-dashboard.eea.europa.eu/ is now only used to browse historical data 2014-2019. The sandbox which was provided for Member states to harvest INSPIRE metadata records and generate the monitoring files (including ETF validation) is not available anymore since last monitoring updates.
