### ISSUE TITLE
Dashboard / Create dashboard for 2016

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/daobs#95]
In https://github.com/INSPIRE-MIF/banana/tree/daobs-1.0.x/filteredResources/app/dashboards create 3 dashboards for 2015 monitoring. There is no automatic processing, so copy/paste old ones is probably the easiest for now.

![image](https://cloud.githubusercontent.com/assets/1701393/13841904/bfd94ee6-ec2b-11e5-8c9c-c98d10a7b3f5.png)

In past dashboard, update the links to add 2015
![image](https://cloud.githubusercontent.com/assets/1701393/13841888/a84ade48-ec2b-11e5-97ba-8515220732d3.png)

See
https://github.com/INSPIRE-MIF/banana/blob/daobs-1.0.x/filteredResources/app/dashboards/INSPIRE-Dashboard-2010-00.json#L150

Also add 2015 in the map dashboard
https://inspire-dashboard.eea.europa.eu/dashboard/dashboard2/#/dashboard/solr/INSPIRE%20indicator%20trends%20(map)

**Comment by pvgenuchten** [comment]
@fxprunayre about the map dashboard, now it fits quite well 2012,1013,2014 next to each other on one row, do you want to remove 2012 to add 2015 there, or make each map 3 (out of 12) cols wide or add a new row for 2015

**Comment by fxprunayre** [comment]
Maybe we could do one dashboard with 2010-2012 and one with 2013-2015 and with links to go from one to another ?

**Comment by pvgenuchten** [comment]
it will be quite empty the first year, but it makes sense, ok will implement in that way
